# alembic.ini
[alembic]
# path to migration scripts
script_location = alembic

# template for revision files
# file_template = %%(rev)s_%%(slug)s

# The auto-generate feature, which allows Alembic to detect changes in your models
# and automatically generate a migration script.
# Set to true to enable.
autogenerate = true

# Where to store the revision history table.
# This defaults to "alembic_version"
version_table_schema =

# The URL to connect to the database.
# For SQLite, it usually looks like this:
# sqlalchemy.url = sqlite:///./sql_app.db <--- 이 라인을 주석 처리하거나 삭제합니다.
sqlalchemy.url =

[loggers]
keys = root, alembic, sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S