"""Change all UUIDs to str for SQLite compatibility

Revision ID: 39ea918598cd
Revises: 
Create Date: 2025-11-05 22:20:24.991481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from diag_project.models import *

# revision identifiers, used by Alembic.
revision: str = '39ea918598cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_personas',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('age_range', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('coaching_style', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coach_personas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_personas_name'), ['name'], unique=False)

    op.create_table('coaches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('character_tags', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coaches_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_coaches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coaches_name'), ['name'], unique=False)

    op.create_table('competencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competencies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competencies_name'), ['name'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('group_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_group_code'), ['group_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_name'), ['name'], unique=True)

    op.create_table('question_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_categories_name'), ['name'], unique=True)

    op.create_table('diagnosis_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coach_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_templates_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_templates_name'), ['name'], unique=True)

    op.create_table('indicators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('levels', sa.JSON(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('competency_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicators_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicators_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicators_name'), ['name'], unique=False)

    op.create_table('participants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('age_group', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_participants_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_id'), ['id'], unique=False)

    op.create_table('diagnoses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_template_id', sa.Uuid(), nullable=False),
    sa.Column('coach_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_template_id'], ['diagnosis_templates.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnoses_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnoses_diagnosis_template_id'), ['diagnosis_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnoses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnoses_participant_id'), ['participant_id'], unique=False)

    op.create_table('diagnosis_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('question_type', sa.Enum('SITUATION_CHOICE', 'OPEN_ENDED', name='questiontype'), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('diagnosis_template_id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.Uuid(), nullable=True),
    sa.Column('indicator_id', sa.Uuid(), nullable=True),
    sa.Column('question_category_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_template_id'], ['diagnosis_templates.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.ForeignKeyConstraint(['question_category_id'], ['question_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_questions_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_questions_diagnosis_template_id'), ['diagnosis_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_questions_indicator_id'), ['indicator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_questions_question_category_id'), ['question_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_questions_question_text'), ['question_text'], unique=False)

    op.create_table('diagnosis_feedbacks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('diagnosis_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feedback_text', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis_feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_feedbacks_diagnosis_id'), ['diagnosis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_feedbacks_id'), ['id'], unique=False)

    op.create_table('diagnosis_results',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('diagnosis_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('competency_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('indicator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_results_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_results_diagnosis_id'), ['diagnosis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_results_indicator_id'), ['indicator_id'], unique=False)

    op.create_table('question_choices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('choice_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['diagnosis_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_choices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_choices_question_id'), ['question_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('coach_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_diagnosis_id'), ['diagnosis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_participant_id'), ['participant_id'], unique=False)

    op.create_table('evaluation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('feedback_summary', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('competency_scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_results_session_id'), ['session_id'], unique=True)

    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('sender_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('competency_id', sa.Uuid(), nullable=True),
    sa.Column('indicator_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_indicator_id'), ['indicator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_session_id'), ['session_id'], unique=False)

    op.create_table('participant_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('selected_choice_id', sa.Uuid(), nullable=True),
    sa.Column('answer_text', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('response_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['diagnosis_questions.id'], ),
    sa.ForeignKeyConstraint(['selected_choice_id'], ['question_choices.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participant_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_answers_diagnosis_id'), ['diagnosis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participant_answers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participant_answers_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participant_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participant_answers_selected_choice_id'), ['selected_choice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participant_answers_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_answers_session_id'))
        batch_op.drop_index(batch_op.f('ix_participant_answers_selected_choice_id'))
        batch_op.drop_index(batch_op.f('ix_participant_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_participant_answers_participant_id'))
        batch_op.drop_index(batch_op.f('ix_participant_answers_id'))
        batch_op.drop_index(batch_op.f('ix_participant_answers_diagnosis_id'))

    op.drop_table('participant_answers')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_messages_indicator_id'))
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_competency_id'))

    op.drop_table('messages')
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_results_session_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_results_id'))

    op.drop_table('evaluation_results')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_participant_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_diagnosis_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_coach_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('question_choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_choices_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_choices_id'))

    op.drop_table('question_choices')
    with op.batch_alter_table('diagnosis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_results_indicator_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_results_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_results_diagnosis_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_results_competency_id'))

    op.drop_table('diagnosis_results')
    with op.batch_alter_table('diagnosis_feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_feedbacks_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_feedbacks_diagnosis_id'))

    op.drop_table('diagnosis_feedbacks')
    with op.batch_alter_table('diagnosis_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_questions_question_text'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_questions_question_category_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_questions_indicator_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_questions_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_questions_diagnosis_template_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_questions_competency_id'))

    op.drop_table('diagnosis_questions')
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnoses_participant_id'))
        batch_op.drop_index(batch_op.f('ix_diagnoses_id'))
        batch_op.drop_index(batch_op.f('ix_diagnoses_diagnosis_template_id'))
        batch_op.drop_index(batch_op.f('ix_diagnoses_coach_id'))

    op.drop_table('diagnoses')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_id'))
        batch_op.drop_index(batch_op.f('ix_participants_group_id'))
        batch_op.drop_index(batch_op.f('ix_participants_email'))

    op.drop_table('participants')
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicators_name'))
        batch_op.drop_index(batch_op.f('ix_indicators_id'))
        batch_op.drop_index(batch_op.f('ix_indicators_competency_id'))

    op.drop_table('indicators')
    with op.batch_alter_table('diagnosis_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_templates_name'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_templates_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_templates_coach_id'))

    op.drop_table('diagnosis_templates')
    with op.batch_alter_table('question_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_categories_name'))
        batch_op.drop_index(batch_op.f('ix_question_categories_id'))

    op.drop_table('question_categories')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_name'))
        batch_op.drop_index(batch_op.f('ix_groups_id'))
        batch_op.drop_index(batch_op.f('ix_groups_group_code'))

    op.drop_table('groups')
    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competencies_name'))
        batch_op.drop_index(batch_op.f('ix_competencies_id'))

    op.drop_table('competencies')
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coaches_name'))
        batch_op.drop_index(batch_op.f('ix_coaches_id'))
        batch_op.drop_index(batch_op.f('ix_coaches_email'))

    op.drop_table('coaches')
    with op.batch_alter_table('coach_personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_personas_name'))

    op.drop_table('coach_personas')
    # ### end Alembic commands ###
