"""Update models with GUID and timestamp

Revision ID: 3cb88da2baea
Revises: 39ea918598cd
Create Date: 2025-11-06 12:17:32.086175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
from diag_project.models.uuid_type import GUID
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3cb88da2baea'
down_revision: Union[str, Sequence[str], None] = '39ea918598cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coach_id', GUID(), nullable=True))
        batch_op.add_column(sa.Column('prompt_template', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=50),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_coach_personas_name'))
        batch_op.create_index(batch_op.f('ix_coach_personas_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_personas_id'), ['id'], unique=False)
        batch_op.create_foreign_key('fk_coach_personas_coach_id', 'coaches', ['coach_id'], ['id'])
        batch_op.drop_column('gender')
        batch_op.drop_column('coaching_style')
        batch_op.drop_column('age_range')

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2000),
               existing_nullable=True)
        batch_op.alter_column('character_tags',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_coaches_name'))

    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_competencies_name'))

    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('participant_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('diagnosis_template_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('coach_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('in_progress', 'completed', 'cancelled', name='diagnosisstatus'),
               existing_nullable=False)

    with op.batch_alter_table('diagnosis_feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=50),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('diagnosis_id',
               existing_type=sa.VARCHAR(),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('feedback_text',
               existing_type=sa.VARCHAR(length=1000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2000),
               existing_nullable=False)

    with op.batch_alter_table('diagnosis_questions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('diagnosis_template_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('question_category_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_diagnosis_questions_competency_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_questions_indicator_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_questions_question_text'))
        #batch_op.drop_constraint('fk_diagnosis_questions_diagnosis_id', type_='foreignkey')
        #batch_op.drop_constraint('fk_diagnosis_questions_diagnosis_id', type_='foreignkey')
        batch_op.drop_column('indicator_id')
        batch_op.drop_column('competency_id')

    with op.batch_alter_table('diagnosis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
        batch_op.add_column(sa.Column('feedback_text', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=50),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('diagnosis_id',
               existing_type=sa.VARCHAR(),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('competency_id',
               existing_type=sa.VARCHAR(),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('indicator_id',
               existing_type=sa.VARCHAR(),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
        batch_op.drop_column('results')

    with op.batch_alter_table('diagnosis_templates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('coach_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_diagnosis_templates_name'))

    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
        batch_op.add_column(sa.Column('recommendations', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('session_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               nullable=True)
        batch_op.drop_column('feedback_summary')
        batch_op.drop_column('competency_scores')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('group_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('competency_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_indicators_name'))
        batch_op.drop_column('examples')
        batch_op.drop_column('levels')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', GUID(), nullable=True))
        batch_op.add_column(sa.Column('diagnosis_id', GUID(), nullable=True))
        batch_op.add_column(sa.Column('question_id', GUID(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messagerole'), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('session_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('competency_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=True)
        batch_op.alter_column('indicator_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_messages_diagnosis_id'), ['diagnosis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_question_id'), ['question_id'], unique=False)
        batch_op.create_foreign_key('fk_messages_participant_id', 'participants', ['participant_id'], ['id'])
        batch_op.create_foreign_key('fk_messages_diagnosis_id', 'diagnoses', ['diagnosis_id'], ['id'])
        batch_op.create_foreign_key('fk_messages_question_id', 'diagnosis_questions', ['question_id'], ['id'])
        batch_op.drop_column('sender_type')
        batch_op.drop_column('sent_at')

    with op.batch_alter_table('participant_answers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('participant_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('diagnosis_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('question_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('session_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=True)
        batch_op.alter_column('selected_choice_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=True)
        batch_op.alter_column('answer_text',
               existing_type=sa.VARCHAR(length=5000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.VARCHAR(),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('male', 'female', 'other', name='genderenum'),
               existing_nullable=True)
        batch_op.alter_column('age_group',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('teens', 'twenties', 'thirties', 'forties', 'fifties', 'sixties_plus', name='agegroupenum'),
               existing_nullable=True)

    with op.batch_alter_table('question_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('question_choices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_num', sa.Integer(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('question_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               nullable=True)
        batch_op.drop_column('order')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=False)
        batch_op.alter_column('participant_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('diagnosis_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               existing_nullable=True)
        batch_op.alter_column('coach_id',
               existing_type=sa.CHAR(length=32),
               type_= GUID(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='sessionstatus'),
               existing_nullable=False)
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='sessionstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('coach_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('diagnosis_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('participant_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('notes')

    with op.batch_alter_table('question_choices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), nullable=False))
        batch_op.alter_column('question_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('order_num')

    with op.batch_alter_table('question_categories', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.alter_column('age_group',
               existing_type=sa.Enum('teens', 'twenties', 'thirties', 'forties', 'fifties', 'sixties_plus', name='agegroupenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.Enum('male', 'female', 'other', name='genderenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type= GUID(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('participant_answers', schema=None) as batch_op:
        batch_op.alter_column('answer_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
        batch_op.alter_column('selected_choice_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('session_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('question_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('diagnosis_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('participant_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('sender_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_msg_participant_id', type_='foreignkey') # 이름 수정
        batch_op.drop_constraint('fk_msg_diagnosis_id', type_='foreignkey') # 이름 수정
        batch_op.drop_constraint('fk_msg_question_id', type_='foreignkey') # 이름 수정
        batch_op.drop_index(batch_op.f('ix_messages_question_id'))
        batch_op.drop_index(batch_op.f('ix_messages_participant_id'))
        batch_op.drop_index(batch_op.f('ix_messages_diagnosis_id'))
        batch_op.alter_column('indicator_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('competency_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('session_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')
        batch_op.drop_column('question_id')
        batch_op.drop_column('diagnosis_id')
        batch_op.drop_column('participant_id')

    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('levels', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('examples', sqlite.JSON(), nullable=False))
        batch_op.create_index(batch_op.f('ix_indicators_name'), ['name'], unique=False)
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('competency_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('group_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competency_scores', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('feedback_summary', sa.VARCHAR(length=1000), nullable=True))
        batch_op.alter_column('session_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('recommendations')
        batch_op.drop_column('summary')

    with op.batch_alter_table('diagnosis_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_templates_name'), ['name'], unique=1)
        batch_op.alter_column('coach_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('diagnosis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('results', sqlite.JSON(), nullable=False))
        batch_op.alter_column('score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('indicator_id',
               existing_type= GUID(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('competency_id',
               existing_type= GUID(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('diagnosis_id',
               existing_type= GUID(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('feedback_text')
        batch_op.drop_column('result_type')

    with op.batch_alter_table('diagnosis_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competency_id', sa.CHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('indicator_id', sa.CHAR(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'competencies', ['competency_id'], ['id'])
        batch_op.create_foreign_key(None, 'indicators', ['indicator_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_diagnosis_questions_question_text'), ['question_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_questions_indicator_id'), ['indicator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_questions_competency_id'), ['competency_id'], unique=False)
        batch_op.alter_column('question_category_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('diagnosis_template_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('diagnosis_feedbacks', schema=None) as batch_op:
        batch_op.alter_column('feedback_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.alter_column('diagnosis_id',
               existing_type= GUID(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('rating')

    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('in_progress', 'completed', 'cancelled', name='diagnosisstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('coach_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('diagnosis_template_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('participant_id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competencies_name'), ['name'], unique=False)
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coaches_name'), ['name'], unique=False)
        batch_op.alter_column('character_tags',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('coach_personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_range', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('coaching_style', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_coach_personas_coach_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_coach_personas_id'))
        batch_op.drop_index(batch_op.f('ix_coach_personas_coach_id'))
        batch_op.create_index(batch_op.f('ix_coach_personas_name'), ['name'], unique=False)
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type= GUID(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('prompt_template')
        batch_op.drop_column('coach_id')

    # ### end Alembic commands ###
