"""add Event table and Phase 3-A fields to ChatMessage

Revision ID: 6c6bec064039
Revises: 3cb88da2baea
Create Date: 2026-04-28 10:05:33.649614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import diag_project.models.uuid_type
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6c6bec064039'
down_revision: Union[str, Sequence[str], None] = '3cb88da2baea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', diag_project.models.uuid_type.GUID(), nullable=True))
        batch_op.add_column(sa.Column('chapter', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('competency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('msg_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_messages_event_id'), ['event_id'], unique=False)
        batch_op.create_foreign_key('fk_chat_messages_event_id', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_messages_event_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_messages_event_id'))
        batch_op.drop_column('msg_type')
        batch_op.drop_column('competency_key')
        batch_op.drop_column('chapter')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
